# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightinfosystem', '0005_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='flightstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flightinfosystem.FlightsStatus', verbose_name='Рейс'),
        ),
    ]
