# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightinfosystem', '0006_checkin_flightstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsstatus',
            name='checkinclass',
            field=models.CharField(blank=True, max_length=15, verbose_name='Класс регистрации'),
        ),
        migrations.AddField(
            model_name='flightsstatus',
            name='endchecktime',
            field=models.TimeField(null=True, verbose_name='Конец регистрации'),
        ),
        migrations.AddField(
            model_name='flightsstatus',
            name='starchecktime',
            field=models.TimeField(null=True, verbose_name='Начало регистрации'),
        ),
        migrations.AlterField(
            model_name='flightsstatus',
            name='statuscheckin',
            field=models.BooleanField(default=False, verbose_name='Статус процесса регистрации'),
        ),
    ]
