# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightinfosystem', '0007_auto_20160624_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaggegeFlightStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starchecktime', models.TimeField(null=True, verbose_name='Начало выдачи')),
                ('endchecktime', models.TimeField(null=True, verbose_name='Конец выдачи')),
                ('checkins', models.CharField(blank=True, max_length=13, verbose_name='Используемая карусель')),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightinfosystem.Flights', verbose_name='Рейс')),
            ],
        ),
        migrations.CreateModel(
            name='BoardFlightStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starchecktime', models.TimeField(null=True, verbose_name='Начало посадки')),
                ('endchecktime', models.TimeField(null=True, verbose_name='Конец посадки')),
                ('checkins', models.CharField(blank=True, max_length=13, verbose_name='Используемый выход')),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightinfosystem.Flights', verbose_name='Рейс')),
            ],
        ),
        migrations.CreateModel(
            name='CheckinFlightStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starchecktime', models.TimeField(null=True, verbose_name='Начало регистрации')),
                ('endchecktime', models.TimeField(null=True, verbose_name='Конец регистрации')),
                ('checkins', models.CharField(blank=True, max_length=13, verbose_name='Используемые стойки регистрации')),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightinfosystem.Flights', verbose_name='Рейс')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='flightstatus',
        ),
        migrations.RemoveField(
            model_name='flightsstatus',
            name='baggage',
        ),
        migrations.RemoveField(
            model_name='flightsstatus',
            name='checkinclass',
        ),
        migrations.RemoveField(
            model_name='flightsstatus',
            name='checkins',
        ),
        migrations.RemoveField(
            model_name='flightsstatus',
            name='endchecktime',
        ),
        migrations.RemoveField(
            model_name='flightsstatus',
            name='gate',
        ),
        migrations.RemoveField(
            model_name='flightsstatus',
            name='starchecktime',
        ),
        migrations.AddField(
            model_name='checkin',
            name='classcheckin',
            field=models.CharField(blank=True, max_length=15, verbose_name='Классность'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='fly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flightinfosystem.CheckinFlightStatus', verbose_name='Рейс'),
        ),
    ]
