# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightinfosystem', '0008_auto_20160624_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='fly',
            new_name='checkinfly',
        ),
    ]
