# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightinfosystem', '0009_auto_20160624_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baggegeflightstatus',
            name='fly',
        ),
        migrations.RemoveField(
            model_name='boardflightstatus',
            name='fly',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkinfly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightinfosystem.CheckinFlightStatus', verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='fullname',
            field=models.CharField(editable=False, max_length=21, verbose_name='Полное имя стойки'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='num',
            field=models.IntegerField(editable=False, verbose_name='Номер стойки'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='shortname',
            field=models.CharField(editable=False, max_length=5, verbose_name='Короткое имя стойки'),
        ),
        migrations.AlterField(
            model_name='checkinflightstatus',
            name='fly',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flightinfosystem.Flights', verbose_name='Рейс'),
        ),
        migrations.AlterField(
            model_name='flightsstatus',
            name='fly',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flightinfosystem.Flights', verbose_name='Рейс'),
        ),
        migrations.DeleteModel(
            name='BaggegeFlightStatus',
        ),
        migrations.DeleteModel(
            name='BoardFlightStatus',
        ),
    ]
