# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightinfosystem', '0010_auto_20160629_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='fullname',
            field=models.CharField(max_length=21, verbose_name='Полное имя стойки'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='num',
            field=models.IntegerField(verbose_name='Номер стойки'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='shortname',
            field=models.CharField(max_length=5, verbose_name='Короткое имя стойки'),
        ),
    ]
