# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightinfosystem', '0011_auto_20160629_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkinfly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightinfosystem.CheckinFlightStatus', verbose_name='Рейс'),
        ),
    ]
